"""Configuration subpackage for bot-commander."""

from .constants import (
    CONFIRMED_SENTINEL,
    DEFAULT_CONVERSATION_TIMEOUT,
    ERR_COMMAND_DISABLED,
    ERR_CONVERSATION_EXPIRED,
    ERR_OPERATION_CANCELLED,
    ERR_UNKNOWN_COMMAND,
    KEY_ALLOWED_JIDS,
    KEY_ALLOWED_USER_IDS,
    KEY_BOT_TOKEN,
    KEY_CHANNEL_ID,
    KEY_DEFAULT_RECEIVER,
    KEY_JID,
    KEY_PASSWORD,
    LOG_BOT_DISABLED,
    LOG_BOT_STARTED,
    LOG_BOT_STOPPED,
)

__all__ = [
    "CONFIRMED_SENTINEL",
    "DEFAULT_CONVERSATION_TIMEOUT",
    "ERR_COMMAND_DISABLED",
    "ERR_CONVERSATION_EXPIRED",
    "ERR_OPERATION_CANCELLED",
    "ERR_UNKNOWN_COMMAND",
    "KEY_ALLOWED_JIDS",
    "KEY_ALLOWED_USER_IDS",
    "KEY_BOT_TOKEN",
    "KEY_CHANNEL_ID",
    "KEY_DEFAULT_RECEIVER",
    "KEY_JID",
    "KEY_PASSWORD",
    "LOG_BOT_DISABLED",
    "LOG_BOT_STARTED",
    "LOG_BOT_STOPPED",
]
